# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmThuc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ten', models.CharField(max_length=265, verbose_name='Ten')),
                ('trangthai', models.BooleanField(verbose_name='TrangThai')),
            ],
            options={
                'db_table': 'AmThuc',
            },
        ),
        migrations.CreateModel(
            name='LuaChon_SanPham',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ten', models.CharField(max_length=265, verbose_name='Ten')),
            ],
            options={
                'db_table': 'LuaChon_SanPham',
            },
        ),
        migrations.CreateModel(
            name='QuanHuyen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ten', models.CharField(max_length=265, verbose_name='Ten')),
                ('trangthai', models.BooleanField(verbose_name='TrangThai')),
            ],
            options={
                'db_table': 'QuanHuyen',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('user_cuahang_id', models.IntegerField(verbose_name='User_CuaHang')),
                ('danhmuc_id', models.IntegerField(verbose_name='DanhMuc_Id')),
                ('tensanpham', models.CharField(max_length=265, verbose_name='TenSanPham')),
                ('hinhanh', models.CharField(max_length=265, verbose_name='HinhAnh')),
                ('ngaydang', models.DateField(verbose_name='NgayDang')),
                ('soluong', models.IntegerField(verbose_name='SoLuong')),
                ('amthuc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.AmThuc')),
            ],
            options={
                'db_table': 'SanPham',
            },
        ),
        migrations.CreateModel(
            name='SanPham_BaoMat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ten', models.CharField(max_length=265, verbose_name='Ten')),
            ],
            options={
                'db_table': 'SanPham_BaoMat',
            },
        ),
        migrations.CreateModel(
            name='SanPham_Gia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('sanpham_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.SanPham')),
            ],
            options={
                'db_table': 'SanPham_Gia',
            },
        ),
        migrations.CreateModel(
            name='SanPham_Gia_ChiTiet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('gia', models.FloatField(verbose_name='Gia')),
                ('ngaybd', models.DateField(verbose_name='NgayBatDau')),
                ('ngaykt', models.DateField(verbose_name='NgayKetThuc')),
                ('is_active', models.BooleanField(verbose_name='Active')),
                ('sanpham_gia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.SanPham_Gia')),
            ],
            options={
                'db_table': 'SanPham_Gia_ChiTiet',
            },
        ),
        migrations.CreateModel(
            name='SanPham_TrangThai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('trangthai', models.BooleanField(verbose_name='TrangThai')),
            ],
            options={
                'db_table': 'SanPham_TrangThai',
            },
        ),
        migrations.CreateModel(
            name='TheLoai_SanPham',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ten', models.CharField(max_length=265, verbose_name='Ten')),
                ('link', models.CharField(max_length=265, verbose_name='Link')),
                ('trangthai', models.BooleanField(verbose_name='TrangThai')),
            ],
            options={
                'db_table': 'TheLoai_SanPham',
            },
        ),
        migrations.CreateModel(
            name='TinhThanh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ten', models.CharField(max_length=265, verbose_name='Ten')),
                ('trangthai', models.BooleanField(verbose_name='TrangThai')),
            ],
            options={
                'db_table': 'TinhThanh',
            },
        ),
        migrations.AddField(
            model_name='sanpham',
            name='baomat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.SanPham_BaoMat'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='quanhuyen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.QuanHuyen'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='theloai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.TheLoai_SanPham'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='tinhthanh_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.TinhThanh'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='trangthai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.SanPham_TrangThai'),
        ),
        migrations.AddField(
            model_name='quanhuyen',
            name='tinh_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.TinhThanh'),
        ),
        migrations.AddField(
            model_name='luachon_sanpham',
            name='sanpham_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.SanPham'),
        ),
    ]
