# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='sdt',
            field=models.IntegerField(verbose_name='SDT'),
        ),
    ]
