# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('tendangnhap', models.CharField(max_length=265, verbose_name='TenDN')),
                ('matkhau', models.CharField(max_length=265, verbose_name='MatKhau')),
                ('role_id', models.IntegerField(verbose_name='Role_Id')),
            ],
            options={
                'db_table': 'TaiKhoan',
            },
        ),
    ]
