# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('taikhoan_id', models.IntegerField(verbose_name='TaiKhoan_Id')),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='HoatDong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ten', models.CharField(max_length=265, verbose_name='Ten')),
            ],
            options={
                'db_table': 'HoatDong',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ten', models.CharField(max_length=265, verbose_name='Ten')),
            ],
            options={
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Module_HoatDong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('hoatdong_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.HoatDong')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Module')),
            ],
            options={
                'db_table': 'Module_HoatDong',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ten', models.CharField(max_length=265, verbose_name='Ten')),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Role_Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Module')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Role')),
            ],
            options={
                'db_table': 'Role_Module',
            },
        ),
    ]
