# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('danhmuccha', models.IntegerField(verbose_name='DanhMucCha')),
                ('tendanhmuc', models.CharField(max_length=265, verbose_name='TenDanhMuc')),
                ('link', models.CharField(max_length=265, verbose_name='Link')),
                ('trangthai', models.BooleanField(verbose_name='TrangThai')),
            ],
            options={
                'db_table': 'DanhMuc',
            },
        ),
    ]
